apiVersion: v1
kind: Namespace 
metadata:
  name: lab-ele
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-test-ele
  namespace: lab-ele
  labels:
    app: backend-nest-test-eletiqueta
spec: 
  replicas: 2 
  selector: 
    matchLabels:
      app: backend-nest-test-eletiqueta
  template:
    metadata:
      labels:
        app: backend-nest-test-eletiqueta
    spec:
      containers:
      - name: backend-nest-test-elecontainer
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-test-ele
        imagePullPolicy: Always 
      imagePullSecrets: 
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nest-test-eleservice
  namespace: lab-ele
  labels:
    app: backend-nest-test-eleservice
spec:
  selector: 
    app: backend-nest-test-eletiqueta
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-backend-nest-test-ele
  namespace: lab-ele
spec:
  ingressClassName: nginx
  rules:
  - host: ele.devops.cl
    http: 
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
           service:
            name: backend-nest-test-eleservice
            port:
              number: 80